// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/login" | "/blog" | "/contacto" | "/cuenta" | "/cuenta/ingresar" | "/cuenta/recuperar" | "/cuenta/registro" | "/galeria" | "/portfolio" | "/portfolio/[category]" | "/portfolio/[category]/[subcategory]" | "/series" | "/series/[slug]" | "/series/[slug]/[subslug]" | "/sesion" | "/sobre-mi" | "/tienda" | "/tienda/carrito" | "/tienda/error" | "/tienda/exito" | "/tienda/pendiente"
type AppRouteHandlerRoutes = "/api/cloudinary/delete" | "/api/cloudinary/upload" | "/api/mercadopago/create-preference" | "/api/mercadopago/webhook" | "/api/orders/sync-payment"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/blog" | "/contacto" | "/cuenta" | "/galeria" | "/portfolio" | "/series" | "/sesion" | "/sobre-mi" | "/tienda" | "/tienda/error" | "/tienda/exito" | "/tienda/pendiente"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/login": {}
  "/api/cloudinary/delete": {}
  "/api/cloudinary/upload": {}
  "/api/mercadopago/create-preference": {}
  "/api/mercadopago/webhook": {}
  "/api/orders/sync-payment": {}
  "/blog": {}
  "/contacto": {}
  "/cuenta": {}
  "/cuenta/ingresar": {}
  "/cuenta/recuperar": {}
  "/cuenta/registro": {}
  "/galeria": {}
  "/portfolio": {}
  "/portfolio/[category]": { "category": string; }
  "/portfolio/[category]/[subcategory]": { "category": string; "subcategory": string; }
  "/series": {}
  "/series/[slug]": { "slug": string; }
  "/series/[slug]/[subslug]": { "slug": string; "subslug": string; }
  "/sesion": {}
  "/sobre-mi": {}
  "/tienda": {}
  "/tienda/carrito": {}
  "/tienda/error": {}
  "/tienda/exito": {}
  "/tienda/pendiente": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/blog": never
  "/contacto": never
  "/cuenta": never
  "/galeria": never
  "/portfolio": never
  "/series": never
  "/sesion": never
  "/sobre-mi": never
  "/tienda": never
  "/tienda/error": never
  "/tienda/exito": never
  "/tienda/pendiente": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
