// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/admin/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/login">> = Specific
  const handler = {} as typeof import("../../app/admin/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog">> = Specific
  const handler = {} as typeof import("../../app/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/contacto/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contacto">> = Specific
  const handler = {} as typeof import("../../app/contacto/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/cuenta/ingresar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cuenta/ingresar">> = Specific
  const handler = {} as typeof import("../../app/cuenta/ingresar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/cuenta/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cuenta">> = Specific
  const handler = {} as typeof import("../../app/cuenta/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/cuenta/recuperar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cuenta/recuperar">> = Specific
  const handler = {} as typeof import("../../app/cuenta/recuperar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/cuenta/registro/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cuenta/registro">> = Specific
  const handler = {} as typeof import("../../app/cuenta/registro/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/galeria/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/galeria">> = Specific
  const handler = {} as typeof import("../../app/galeria/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/portfolio/[category]/[subcategory]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portfolio/[category]/[subcategory]">> = Specific
  const handler = {} as typeof import("../../app/portfolio/[category]/[subcategory]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/portfolio/[category]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portfolio/[category]">> = Specific
  const handler = {} as typeof import("../../app/portfolio/[category]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/portfolio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/portfolio">> = Specific
  const handler = {} as typeof import("../../app/portfolio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/series/[slug]/[subslug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/series/[slug]/[subslug]">> = Specific
  const handler = {} as typeof import("../../app/series/[slug]/[subslug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/series/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/series/[slug]">> = Specific
  const handler = {} as typeof import("../../app/series/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/series/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/series">> = Specific
  const handler = {} as typeof import("../../app/series/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/sesion/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sesion">> = Specific
  const handler = {} as typeof import("../../app/sesion/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/sobre-mi/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/sobre-mi">> = Specific
  const handler = {} as typeof import("../../app/sobre-mi/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/tienda/carrito/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tienda/carrito">> = Specific
  const handler = {} as typeof import("../../app/tienda/carrito/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/tienda/error/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tienda/error">> = Specific
  const handler = {} as typeof import("../../app/tienda/error/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/tienda/exito/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tienda/exito">> = Specific
  const handler = {} as typeof import("../../app/tienda/exito/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/tienda/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tienda">> = Specific
  const handler = {} as typeof import("../../app/tienda/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/tienda/pendiente/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tienda/pendiente">> = Specific
  const handler = {} as typeof import("../../app/tienda/pendiente/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cloudinary/delete/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cloudinary/delete">> = Specific
  const handler = {} as typeof import("../../app/api/cloudinary/delete/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cloudinary/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cloudinary/upload">> = Specific
  const handler = {} as typeof import("../../app/api/cloudinary/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/mercadopago/create-preference/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mercadopago/create-preference">> = Specific
  const handler = {} as typeof import("../../app/api/mercadopago/create-preference/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/mercadopago/webhook/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/mercadopago/webhook">> = Specific
  const handler = {} as typeof import("../../app/api/mercadopago/webhook/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/orders/sync-payment/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/orders/sync-payment">> = Specific
  const handler = {} as typeof import("../../app/api/orders/sync-payment/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/blog/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/blog">> = Specific
  const handler = {} as typeof import("../../app/blog/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/contacto/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/contacto">> = Specific
  const handler = {} as typeof import("../../app/contacto/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/cuenta/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/cuenta">> = Specific
  const handler = {} as typeof import("../../app/cuenta/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/galeria/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/galeria">> = Specific
  const handler = {} as typeof import("../../app/galeria/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/portfolio/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/portfolio">> = Specific
  const handler = {} as typeof import("../../app/portfolio/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/series/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/series">> = Specific
  const handler = {} as typeof import("../../app/series/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/sesion/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/sesion">> = Specific
  const handler = {} as typeof import("../../app/sesion/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/sobre-mi/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/sobre-mi">> = Specific
  const handler = {} as typeof import("../../app/sobre-mi/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/tienda/error/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/tienda/error">> = Specific
  const handler = {} as typeof import("../../app/tienda/error/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/tienda/exito/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/tienda/exito">> = Specific
  const handler = {} as typeof import("../../app/tienda/exito/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/tienda/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/tienda">> = Specific
  const handler = {} as typeof import("../../app/tienda/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/tienda/pendiente/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/tienda/pendiente">> = Specific
  const handler = {} as typeof import("../../app/tienda/pendiente/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
